all:
  hosts:
    cluster-zone1-control-1:
      ansible_host: 51.250.8.234
      ip: 192.168.10.16
      access_ip: 192.168.10.16
    cluster-zone2-work-b-1:
      ansible_host: 51.250.17.98
      ip: 192.168.20.28
      access_ip: 192.168.20.28
    cluster-zone3-work-d-1:
      ansible_host: 84.252.135.61
      ip: 192.168.30.18
      access_ip: 192.168.30.18
  children:
    kube_control_plane:
      hosts:
        cluster-zone1-control-1:
    kube_node:
      hosts:
        cluster-zone2-work-b-1:
        cluster-zone3-work-d-1:
    etcd:
      hosts:
        cluster-zone1-control-1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}